"""add telegram and push fields to users

Revision ID: 0028aabc0bc8
Revises: d8c5b8aff47e
Create Date: 2026-08-15 23:51:43.811378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0028aabc0bc8'
down_revision = 'd8c5b8aff47e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('expo_push_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('telegram_link_code', sa.String(length=16), nullable=True))
    op.create_unique_constraint('uq_users_telegram_link_code', 'users', ['telegram_link_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_telegram_link_code', 'users', type_='unique')
    op.drop_column('users', 'telegram_link_code')
    op.drop_column('users', 'telegram_chat_id')
    op.drop_column('users', 'expo_push_token')
    # ### end Alembic commands ###
