"""add achievement criteria and seed gamification catalog

Revision ID: 4786d73f27e8
Revises: 0028aabc0bc8
Create Date: 2026-08-16 00:05:24.667893

"""
import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4786d73f27e8'
down_revision = '0028aabc0bc8'
branch_labels = None
depends_on = None


achievements_table = sa.table(
    "achievements",
    sa.column("id", postgresql.UUID(as_uuid=True)),
    sa.column("key", sa.String),
    sa.column("name", sa.String),
    sa.column("description", sa.Text),
    sa.column("icon", sa.String),
    sa.column("xp_reward", sa.Integer),
    sa.column("criteria", postgresql.JSONB),
)

challenges_table = sa.table(
    "challenges",
    sa.column("id", postgresql.UUID(as_uuid=True)),
    sa.column("key", sa.String),
    sa.column("title", sa.String),
    sa.column("description", sa.Text),
    sa.column("xp_reward", sa.Integer),
    sa.column("criteria", postgresql.JSONB),
    sa.column("is_active", sa.Boolean),
)

ACHIEVEMENTS = [
    dict(
        key="first_guardian",
        name="First Guardian",
        description="Armed your first asset.",
        icon="shield",
        xp_reward=20,
        criteria={"metric": "asset_arm_count", "target": 1},
    ),
    dict(
        key="case_closed",
        name="Case Closed",
        description="Resolved your first incident.",
        icon="check-circle",
        xp_reward=30,
        criteria={"metric": "incident_resolved_count", "target": 1},
    ),
    dict(
        key="quick_reflexes",
        name="Quick Reflexes",
        description="Disarmed 5 alerts within the 3-second window before they escalated.",
        icon="zap",
        xp_reward=50,
        criteria={"metric": "incident_avoided_count", "target": 5},
    ),
    dict(
        key="streak_starter",
        name="Streak Starter",
        description="Reached a 3-day guardian streak.",
        icon="flame",
        xp_reward=25,
        criteria={"metric": "streak_days", "target": 3},
    ),
    dict(
        key="week_guardian",
        name="Week Guardian",
        description="Reached a 7-day guardian streak.",
        icon="calendar",
        xp_reward=75,
        criteria={"metric": "streak_days", "target": 7},
    ),
]

CHALLENGES = [
    dict(
        key="arm_3_assets",
        title="Arm 3 Assets",
        description="Arm three different assets to build full coverage.",
        xp_reward=30,
        criteria={"metric": "asset_arm_count", "target": 3},
    ),
    dict(
        key="fast_fingers",
        title="Fast Fingers",
        description="Disarm 3 alerts within the window before they escalate.",
        xp_reward=40,
        criteria={"metric": "incident_avoided_count", "target": 3},
    ),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###

    op.bulk_insert(
        achievements_table,
        [{"id": uuid.uuid4(), **row} for row in ACHIEVEMENTS],
    )
    op.bulk_insert(
        challenges_table,
        [{"id": uuid.uuid4(), "is_active": True, **row} for row in CHALLENGES],
    )


def downgrade() -> None:
    op.execute(
        challenges_table.delete().where(
            challenges_table.c.key.in_([row["key"] for row in CHALLENGES])
        )
    )
    op.execute(
        achievements_table.delete().where(
            achievements_table.c.key.in_([row["key"] for row in ACHIEVEMENTS])
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievements', 'criteria')
    # ### end Alembic commands ###
