"""initial schema

Revision ID: d8c5b8aff47e
Revises: 
Create Date: 2026-08-15 22:58:39.560419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8c5b8aff47e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_key'), 'achievements', ['key'], unique=True)
    op.create_table('challenges',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_is_active'), 'challenges', ['is_active'], unique=False)
    op.create_index(op.f('ix_challenges_key'), 'challenges', ['key'], unique=True)
    op.create_table('users',
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('level', sa.Enum('ROOKIE', 'WATCHMAN', 'GUARDIAN', 'SENTINEL', 'HOSTEL_PROTECTOR', name='guardian_level'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('challenge_completions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_completions_challenge_id'), 'challenge_completions', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_challenge_completions_completed_at'), 'challenge_completions', ['completed_at'], unique=False)
    op.create_index(op.f('ix_challenge_completions_user_id'), 'challenge_completions', ['user_id'], unique=False)
    op.create_table('devices',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('device_uid', sa.String(length=64), nullable=False),
    sa.Column('pairing_code', sa.String(length=16), nullable=True),
    sa.Column('status', sa.Enum('UNPAIRED', 'ONLINE', 'OFFLINE', 'DEGRADED', name='device_status'), nullable=False),
    sa.Column('firmware_version', sa.String(length=32), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_uid'), 'devices', ['device_uid'], unique=True)
    op.create_index(op.f('ix_devices_owner_id'), 'devices', ['owner_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('INCIDENT', 'ACHIEVEMENT', 'CHALLENGE', 'DEVICE_HEALTH', 'SYSTEM', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('security_scores',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('ROOKIE', 'WATCHMAN', 'GUARDIAN', 'SENTINEL', 'HOSTEL_PROTECTOR', name='guardian_level'), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('last_calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_scores_user_id'), 'security_scores', ['user_id'], unique=True)
    op.create_table('user_achievements',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('achievement_id', sa.UUID(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    op.create_index(op.f('ix_user_achievements_achievement_id'), 'user_achievements', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_unlocked_at'), 'user_achievements', ['unlocked_at'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('xp_transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('reference_type', sa.String(length=64), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_transactions_created_at'), 'xp_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_xp_transactions_user_id'), 'xp_transactions', ['user_id'], unique=False)
    op.create_table('assets',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('BAG', 'LAPTOP', 'DOCUMENT', 'OTHER', name='asset_category'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=1024), nullable=True),
    sa.Column('is_armed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_device_id'), 'assets', ['device_id'], unique=False)
    op.create_index(op.f('ix_assets_owner_id'), 'assets', ['owner_id'], unique=False)
    op.create_table('device_health',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('UNPAIRED', 'ONLINE', 'OFFLINE', 'DEGRADED', name='device_status'), nullable=False),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('wifi_rssi', sa.Integer(), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.Column('firmware_version', sa.String(length=32), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_health_device_id'), 'device_health', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_health_recorded_at'), 'device_health', ['recorded_at'], unique=False)
    op.create_table('incidents',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'RESOLVED', 'FALSE_ALARM', name='incident_status'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incident_severity'), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_asset_id'), 'incidents', ['asset_id'], unique=False)
    op.create_index(op.f('ix_incidents_device_id'), 'incidents', ['device_id'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_triggered_at'), 'incidents', ['triggered_at'], unique=False)
    op.create_index(op.f('ix_incidents_user_id'), 'incidents', ['user_id'], unique=False)
    op.create_table('sensor_events',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('MOVEMENT', 'HALL_TRIGGER', 'DUAL_VERIFIED', 'DISARMED', 'HEARTBEAT', name='sensor_event_type'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('device_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_events_asset_id'), 'sensor_events', ['asset_id'], unique=False)
    op.create_index(op.f('ix_sensor_events_device_id'), 'sensor_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_sensor_events_event_type'), 'sensor_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_sensor_events_received_at'), 'sensor_events', ['received_at'], unique=False)
    op.create_table('evidence',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('PHOTO', 'SENSOR_SNAPSHOT', 'NOTE', name='evidence_type'), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_captured_at'), 'evidence', ['captured_at'], unique=False)
    op.create_index(op.f('ix_evidence_incident_id'), 'evidence', ['incident_id'], unique=False)
    op.create_table('incident_timeline',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('actor', sa.Enum('SYSTEM', 'USER', 'DEVICE', name='timeline_actor'), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_timeline_incident_id'), 'incident_timeline', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_timeline_occurred_at'), 'incident_timeline', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_timeline_occurred_at'), table_name='incident_timeline')
    op.drop_index(op.f('ix_incident_timeline_incident_id'), table_name='incident_timeline')
    op.drop_table('incident_timeline')
    op.drop_index(op.f('ix_evidence_incident_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_captured_at'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_sensor_events_received_at'), table_name='sensor_events')
    op.drop_index(op.f('ix_sensor_events_event_type'), table_name='sensor_events')
    op.drop_index(op.f('ix_sensor_events_device_id'), table_name='sensor_events')
    op.drop_index(op.f('ix_sensor_events_asset_id'), table_name='sensor_events')
    op.drop_table('sensor_events')
    op.drop_index(op.f('ix_incidents_user_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_triggered_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_device_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_asset_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_device_health_recorded_at'), table_name='device_health')
    op.drop_index(op.f('ix_device_health_device_id'), table_name='device_health')
    op.drop_table('device_health')
    op.drop_index(op.f('ix_assets_owner_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_device_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_xp_transactions_user_id'), table_name='xp_transactions')
    op.drop_index(op.f('ix_xp_transactions_created_at'), table_name='xp_transactions')
    op.drop_table('xp_transactions')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_unlocked_at'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievement_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_security_scores_user_id'), table_name='security_scores')
    op.drop_table('security_scores')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_devices_owner_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_uid'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_challenge_completions_user_id'), table_name='challenge_completions')
    op.drop_index(op.f('ix_challenge_completions_completed_at'), table_name='challenge_completions')
    op.drop_index(op.f('ix_challenge_completions_challenge_id'), table_name='challenge_completions')
    op.drop_table('challenge_completions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_challenges_key'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_is_active'), table_name='challenges')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_achievements_key'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###

    # Postgres ENUM types are independent objects and survive table drops; remove
    # them explicitly so downgrade fully reverses upgrade.
    for enum_name in (
        "guardian_level",
        "device_status",
        "asset_category",
        "sensor_event_type",
        "incident_status",
        "incident_severity",
        "timeline_actor",
        "evidence_type",
        "notification_type",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
